# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://localhost:3306/ry?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
                username: root
                password: password
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url:
                username:
                password:
            statViewServlet:
                # 控制台管理用户名和密码
                login-username: ruoyi
                login-password: 123456
    # redis 配置
    redis:
        # 地址
        host:
        # 端口，默认为6379
        port:
        # 数据库索引
        database:
        # 密码
        password:
ruoyi:
    # 文件路径 示例（ Windows配置C:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
    profile: C:/ruoyi/uploadPath
scheduling:
    enabled: false
#操作oss需要的一些参数
aliyun:
    accessKeyId: 你的accessKeyId       # 阿里云的accessKeyId
    secretAccessKey: 你的accessKey密码   # accessKey 密码
    oss:
        endPoint: 你的endpoint     # Endpoint:在阿里云oss控制台查看自己使用的endpoint
        bucketName: 你的bucketName   # bucket 名称
wechat:
    enabled: false
    appId: 你的微信服务号信息
    secret: 你的微信服务号信息
    merchantId: 微信支付商户号
    privateKeyPath: 微信支付密钥地址相对地址
    merchantSerialNumber: 微信支付密钥对应的序列号
    apiV3key: 微信支付apiV3key
    notifyUrl: 微信支付回调地址
    miniProgramAppId: 小程序apppid
    miniProgramSecret:
sms:
  enabled: false
  # 阿里云 dysmsapi.aliyuncs.com
  endpoint: dysmsapi.aliyuncs.com
  accessKeyId: 你的accessKeyId #阿里云短信服务控制台查看
  accessKeySecret: 你的accessKeySecret #同上
  signName:  签名
  templateId: 模板id
  # 腾讯专用
  sdkAppId:
aes:
  # aes的密钥(长度只能是16或24或32位)
  key: 1111111111111111
